# Generated by Django 5.1 on 2024-10-27 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_classification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic_predict',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='性別'),
        ),
    ]
