# Generated by Django 5.1 on 2024-10-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_classification', '0002_logistic_predict_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic_predict',
            name='education',
            field=models.IntegerField(blank=True, choices=[(0, 'High School'), (1, 'College'), (2, 'Graduate School')], null=True, verbose_name='学歴'),
        ),
        migrations.AddField(
            model_name='logistic_predict',
            name='income',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年収'),
        ),
        migrations.AddField(
            model_name='logistic_predict',
            name='loan',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='借入額'),
        ),
        migrations.AddField(
            model_name='logistic_predict',
            name='loan_history',
            field=models.IntegerField(blank=True, choices=[(0, 'Yes'), (1, 'No')], null=True, verbose_name='過去の借入'),
        ),
        migrations.AddField(
            model_name='logistic_predict',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='氏名'),
        ),
        migrations.AddField(
            model_name='logistic_predict',
            name='occupation',
            field=models.IntegerField(blank=True, choices=[(0, 'Government Worker'), (1, 'Private Sector'), (2, 'Unemployed')], null=True, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='sex',
            field=models.IntegerField(blank=True, choices=[(0, 'Male'), (1, 'Female')], null=True, verbose_name='性別'),
        ),
    ]
