# Generated by Django 5.1 on 2024-10-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_classification', '0003_logistic_predict_education_logistic_predict_income_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logistic_predict',
            name='default_pred',
            field=models.IntegerField(default=0, verbose_name='デフォルトリスク'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='年齢'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='education',
            field=models.IntegerField(choices=[(0, 'High School'), (1, 'College'), (2, 'Graduate School')], default=0, verbose_name='学歴'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='income',
            field=models.PositiveIntegerField(default=0, verbose_name='年収'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='loan',
            field=models.PositiveIntegerField(default=0, verbose_name='借入額'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='loan_history',
            field=models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], default=0, verbose_name='過去の借入'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='name',
            field=models.CharField(default='氏名', max_length=255, verbose_name='氏名'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='occupation',
            field=models.IntegerField(choices=[(0, 'Government Worker'), (1, 'Private Sector'), (2, 'Unemployed')], default=0, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='logistic_predict',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='性別'),
        ),
    ]
