# Generated by Django 5.1 on 2024-12-01 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture_classification', '0004_logistic_predict_default_pred_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='氏名', max_length=255, verbose_name='氏名')),
                ('age', models.PositiveIntegerField(default=0, verbose_name='年齢')),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0, verbose_name='性別')),
                ('education', models.IntegerField(choices=[(0, 'Highschool'), (1, 'Associate'), (2, 'Bachelor'), (3, 'Master'), (4, 'Doctorate')], verbose_name='学歴')),
                ('income', models.PositiveIntegerField(default=0, verbose_name='年収')),
                ('emp_exp', models.PositiveIntegerField(default=0, verbose_name='就業年数')),
                ('loan_amount', models.PositiveIntegerField(default=0, verbose_name='融資額')),
                ('default', models.IntegerField(choices=[(0, 'Yes'), (1, 'No')], verbose_name='不履行歴')),
                ('loan_intent', models.PositiveIntegerField(default=0, verbose_name='利用目的')),
                ('home_ownership', models.PositiveIntegerField(default=0, verbose_name='家')),
                ('loan_status', models.IntegerField(default=0, verbose_name='ローンステータス')),
            ],
        ),
        migrations.DeleteModel(
            name='Logistic_Predict',
        ),
    ]
